baseurl = "https://evornov.github.io/blood.gratis/"
#baseurl = "https://blood.gratis/"
title = "like blood... but free??"
theme = "vncnt-hugo"
publishDir = "public"
# canonifyurls = true
hasCJKLanguage = true
_merge = "none"
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"


[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  meds = "meds/:slug/"

[params]
  author = "blood.gratis"
  email = "hey@blood.gratis"
  description = "??"
  bio = "It's blood, gratis. \nFor when you just can't bring yourself to pay for blood.  "
  avatar = "img/avatar.jpeg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/evornov"
    linkedin = "https://linkedin.com/in/eliana-vornov/"
